#
@baseUrl = http://localhost:3000/api

# Categories

###
# @name GETCategories

GET {{baseUrl}}/categories

###
# @name ADDCategory

POST {{baseUrl}}/categories
Content-Type: application/json

{
    "name": "Máy tính bảng"
}

###
# @name UpdateCategory
 
PATCH  {{baseUrl}}/categories/2
Content-Type: application/json

{
    "name": "Máy tính bảng new"
}
###

# @name DeleteCategory
DELETE {{baseUrl}}/categories/2
 